---
# tasks file for vaultwarden
- name: Ensure docker modul is installed
  pip:
    name: docker

- name: Create vaultwarden container
  docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    state: started
    volumes:
      - ./vw_data/:/data/
    env:
      # Dokumentation aller Environmant Variablen unter https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
      WEBSOCKET_ENABLED: "true" ## Enables websocket notifications
      DOMAIN: https://bitwarden.makerspace-gt.de # It's recommended to configure this value, otherwise certain functionality might not work, like attachment downloads, email links and U2F.

      # SMTP_HOST={{ bwrs_env_smtp_host }}
      # SMTP_FROM={{ bwrs_env_smtp_from }}
      # SMTP_PORT={{ bwrs_env_smtp_port }}
      # SMTP_SSL={{ bwrs_env_smtp_ssl }}
      # SMTP_USERNAME={{ bwrs_env_smtp_username }}
      # SMTP_PASSWORD={{ bwrs_env_smtp_password }}
      # SMTP_EXPLICIT_TLS={{ bwrs_env_smtp_explicit_tls }}
      # SHOW_PASSWORD_HINT={{ bwrs_env_show_password_hint }}

      ## Require new device emails. When a user logs in an email is required to be sent.
      ## If sending the email fails the login attempt will fail!!
      # REQUIRE_DEVICE_EMAIL=false

      ## HIBP Api Key
      ## HaveIBeenPwned API Key, request it here: https://haveibeenpwned.com/API/Key
      # HIBP_API_KEY=

- name: Copy Caddyfile to remote-location
  copy:
    src: ./files/Caddyfile
    dest: ./Caddyfile

- name: Create Caddy container
  docker_container:
    name: caddy
    image: caddy:latest
    state: started
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    env:
      DOMAIN: https://bitwarden.makerspace-gt.de # Your domain, prefixed with http or https.
      EMAIL: info@makerspace-gt.de       # The email address to use for ACME registration.
      LOG_FILE: /data/access.log

- name: create docker network # Has to be added due to docker compose creates this implicit
  docker_network:
    name: vaultwarden
    connected:
      - vaultwarden
      - caddy
